### ISSUE TITLE
Allow cleaning up containers after command succeeds

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor-ecosystem/kantra#20]
We need to think about whether we want to keep the log. I think, for the successful runs, we can safely ignore logs and just clean up the container by default. Can have a flag to not clean up. This also means that we will maintain a handle for the container throughout the lifecycle of the command, I think container name should just be fine.

**Comment by shawn-hurley** [comment]
What about streaming the logs to some other log file? $XDG_HOME/.kantra/.log or something!

**Comment by pranavgaikwad** [comment]
@shawn-hurley yup thats it...thanks!

**Comment by pranavgaikwad** [comment]
Fixed via #29
